services:
  db:
    image: mariadb
    restart: always
    container_name: pomodoroapi_db
    env_file:
      - ~/secrets/docker/pomodoro/.env
    secrets:
      - db_password
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - db-data:/var/lib/mariadb
    networks:
      - app-network
    healthcheck:
      test: mariadb -u root -p$$(cat $$MARIADB_ROOT_PASSWORD_FILE) -e "SHOW DATABASES;"
      interval: 10s
      timeout: 3s
      retries: 5

  server:
    container_name: pomodoroapi_server
    build:
      context: .
      target: final
    expose:
      - 8080
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ~/secrets/docker/pomodoro/.env
    networks:
      - app-network
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    environment:
      ConnectionStrings__DefaultConnection: ${DEFAULT_CONNECTION}
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      DB_MIGRATE_ON_STARTUP: true
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: root
      DB_NAME: pomodoro
      DB_SERVER: db

  web:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    environment:
      API_SERVER: server
    ports:
      - 80:80
      - 443:443
    volumes:
      - ~/templates/nginx:/etc/nginx/templates
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
      - dhparam:/etc/ssl/certs
      - /etc/dhparam:/etc/dhparam
    networks:
      - app-network
    depends_on:
      - server
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 30s
      timeout: 30s
      retries: 5

  certbot:
    image: certbot/certbot:latest
    depends_on:
      web:
        condition: service_healthy
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email sangenshoku.1@gmail.com --agree-tos --no-eff-email --renew-by-default -d pomodoro.rjon.tech

volumes:
  certbot-etc:
  certbot-var:
  web-root:
  dhparam:
    driver: local
    driver_opts:
      type: none
      o: bind
  db-data:

secrets:
  db_connection_string:
    file: ~/secrets/docker/pomodoro/db_connection_string.txt
  db_password:
    file: ~/secrets/docker/pomodoro/db_password.txt

networks:
  app-network:
    name: "pomodoro-network"
    driver: bridge
